### ISSUE TITLE
Deployment plugin and multiple classviews

### ISSUE THREAD

**Issue by mobius3** [DoUML/douml#105]
<a href="https://github.com/Zeks"><img src="https://avatars.githubusercontent.com/u/1160852?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Zeks](https://github.com/Zeks)**
_Friday Feb 01, 2013 at 14:38 GMT_
_Originally opened as https://github.com/leonardo2d/douml/issues/42_

----

Need to make it work for this case

**Comment by habipyesilyurt** [comment]
"Deploy classes" command is working (if it is meant)
