### ISSUE TITLE
Artifact creation

### ISSUE THREAD

**Issue by mobius3** [DoUML/douml#115]
<a href="https://github.com/Zeks"><img src="https://avatars.githubusercontent.com/u/1160852?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Zeks](https://github.com/Zeks)**
_Friday Feb 01, 2013 at 14:49 GMT_
_Originally opened as https://github.com/leonardo2d/douml/issues/55_

----

Should probably ask stuff on creation instead of forcing user to double click and edit everyting

**Comment by habipyesilyurt** [comment]
fixed de547d2
