### ISSUE TITLE
[UI] too many popup windows.

### ISSUE THREAD

**Issue by sergey-shambir** [DoUML/douml#51]
Issue can be reproduced in dialog asking new operation name. If I press "Ok" on empty name, it shows yet one popup and reports "illegal name **or** already used", than it shows popup again.

At first, we can check name correctness right in dialog, and disable "Ok" button while name is incorrect. At second, we should show exact reason why name is incorrect: in QtCreator it usually implemented by passing ```QString *error``` to name validator.

**Comment by habipyesilyurt** [comment]
fixed 34e44c1
