### ISSUE TITLE
Missing i18n support

### ISSUE THREAD

**Issue by glixx** [DoUML/douml#84]
There are compiled *.lang, but no mechanism to add new translation. How to translate?

**Comment by gilbertoca** [comment]
@glixx and @mobius3 I've created the PR, but I didn't understand one thing: How the translation will occur without the lang file?
I thought the PR was to use the TS file. But this line got me confused:
```
translator.load(QString("/usr/share/douml/douml__") + locale);
```

**Comment by glixx** [comment]
```diff
translator.load(QString("/usr/share/douml/douml_") + locale);
```

**Comment by gilbertoca** [comment]
Would you mind to try the PR? Locally is not working!

**Comment by glixx** [comment]
gilbertoca, did you create .qm files?

**Comment by gilbertoca** [comment]
No. What .qm file is? Is It necessary? If so, how to make the changes in the build file?

**Comment by glixx** [comment]
lrelease *.ts
and put *.qm files into /usr/share/douml

> If so, how to make the changes in the build file?

Sometimes authors put ready qm files in sources.

But there is problem: lupdate does not work with current ts files. ts files is not ok and better to mark strings for translations directly in code.

**Comment by gilbertoca** [comment]
> But there is problem: lupdate does not work with current ts files. ts files is not ok and better to > mark strings for translations directly in code.

What do you suggest?

**Comment by glixx** [comment]
Mark all string in code as translatable, create clean ts files by lupdate, import strings from po files to ts files.

**Comment by habipyesilyurt** [comment]
i18n support is added with #139
